(deftheme black-space
  "A colorful dark theme based loosely on cyberpunk and spacemacs themes.")

(custom-theme-set-variables
 'black-space
 '(ansi-color-names-vector ["#0a0814" "#f2241f" "#67b11d" "#b1951d" "#4f97d7" "#a31db1" "#28def0" "#b2b2b2"]))

(custom-theme-set-faces
 'black-space
 '(cursor ((t (:background "#d02090"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444155"))))
 '(region ((((class color) (min-colors 89)) (:background "#444155"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(font-lock-builtin-face ((t (:foreground "#63b8ff"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :background "#000000"))))
 '(font-lock-comment-face ((t (:background "#000000" :foreground "#aaaaaa" "#ba55d3" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#ff00ff"))))
 '(font-lock-doc-face ((t (:foreground "green yellow"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ffff00" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#00bfff" :slant normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#ff8c00"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "spring green"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#9932cc" :inherit bold))))
 '(font-lock-variable-name-face ((t (:foreground "#870ff"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#292b2e"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(fringe ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#212026")))
 '(tooltip ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#222226" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#bc6ec5"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :box (:color "#5d4d7a" :line-width 1)))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#86dc2f"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#29422d" :weight normal))))
 '(match ((((class color) (min-colors 89)) (:background "#444155" :foreground "#86dc2f"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(custom-button ((((class color) (min-colors 89)) :background "#212026" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#292b2e"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-scrollbar-track ((((class color) (min-colors 89)) (:background "#212026"))))
 '(company-tooltip-scrollbar-thumb ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#ce537a"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#4f97d7"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :underline t))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(show-paren-match ((((class color) (min-colors 89)) (:underline "#7cfc00" :inherit bold :foreground "#7cfc00"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold :underline t))))
 '(org-level-1 ((t (:inherit outline-1 :foreground "yellow"))))
 '(org-level-2 ((t (:inherit outline-2 :foreground "deep sky blue"))))
 '(org-level-3 ((t (:inherit outline-3 :foreground "indian red"))))
 '(org-level-4 ((t (:inherit outline-4 :overline nil :underline nil))))
 '(default ((t (:background "#000000" :foreground "#EEEEEE")))))

(provide-theme 'black-space)
